site_name: job_posting
site_description: Job posting from different companies.
repo_url: https://github.com/hoetaek/wanted_pre_onboarding
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/hoetaek">hoetaek</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
